//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAMV_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCategory
    {
        public long ProjectCategoryId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public long EntruBy { get; set; }
        public Nullable<long> CompanyId { get; set; }
    }
}
